Cap1
semanticmx/html5_082021 pull request #1
Opened 2021-09-06 16:43 UTC by JosephColinP

2021-09-06 19:28 UTC, semanticmx commented
@JosephColinP todos los PR tienen que incluir una descripción para saber qué es lo que se va a revisar.

Acabo de agregar un [PR template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) acá: https://raw.githubusercontent.com/semanticmx/html5_082021/main/.github/pull_request_template.md

Los siguientes PR que hagas cargarán esa plantilla para que puedas reemplazarla por la info correspondiente.

2021-09-07 00:15 UTC, semanticmx commented
Perfecto, estaría bueno crear folders por capítulo tipo:

```
chapter 1/
  README-md
  index.html

```

2021-09-07 00:16 UTC, semanticmx requested changes
se ve bien, solo hay que meter los archivos en un folder por capítulo y hay que hacer un README.md general

2021-09-07 00:44 UTC, JosephColinP commented
Valeeeeeeeee!!!! esta bien, sin problema, ahorita  el template, disculpa
por responder hasta ahora



On Mon, Sep 6, 2021 at 7:16 PM Carlos Vences ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> se ve bien, solo hay que meter los archivos en un folder por capítulo y
> hay que hacer un README.md general
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/semanticmx/html5_082021/pull/1#pullrequestreview-747452213>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AVNHCMCQBA4MV66ZOSUERUDUAVKW5ANCNFSM5DQY6VNQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-09-07 00:48 UTC, JosephColinP commented
Aaaah ya ví. Entonces para recapitular

Hago un folder por cada capítulo con su respectivo Readme e Index.
En el archivo Readme pondré la descripción del ejercicio.

Una pregunta, ¿los nombres del branch están bien, requieren más descripción?



On Mon, Sep 6, 2021 at 7:43 PM Joseph Colin ***@***.***> wrote:

> Valeeeeeeeee!!!! esta bien, sin problema, ahorita  el template, disculpa
> por responder hasta ahora
>
>
>
> On Mon, Sep 6, 2021 at 7:16 PM Carlos Vences ***@***.***>
> wrote:
>
>> ***@***.**** requested changes on this pull request.
>>
>> se ve bien, solo hay que meter los archivos en un folder por capítulo y
>> hay que hacer un README.md general
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/semanticmx/html5_082021/pull/1#pullrequestreview-747452213>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AVNHCMCQBA4MV66ZOSUERUDUAVKW5ANCNFSM5DQY6VNQ>
>> .
>> Triage notifications on the go with GitHub Mobile for iOS
>> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
>> or Android
>> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>>
>>
>

2021-09-07 01:46 UTC, closed without merging