Ch. 5 video
semanticmx/html5_082021 pull request #13
Opened 2021-10-13 16:18 UTC by JosephColinP

## what

- Se agregó una carpeta con los archivos index.html, README.md y videos.

## why

- Esto se hizo para entender como subir videos a una página web para ser visualizados en diferentes navegadores

## References

- http://diveintohtml5.info/video.html

2021-10-18 13:44 UTC, semanticmx requested changes
solo hay que ajustar el tag de video

2021-10-18 13:44 UTC, semanticmx commented on cap3-elements/README.md
> +# HTML5 Elements
@JosephColinP acá falló el merge, este archivo es del PR anterior

2021-10-18 13:44 UTC, semanticmx commented on cap5-video/README.md
> +        <video height="500px"
el height va en otra línea.

Puedes agrupar los atributos por tipo, por ejemplo height y width generalmente van juntos

2021-10-18 13:44 UTC, semanticmx commented on cap5-video/index.html
> +        <video height="500px"
igual en este.

2021-10-18 15:04 UTC, JosephColinP commented on cap3-elements/README.md
> +# HTML5 Elements
Aquí me perdí, que tengo que hacer ?

2021-10-18 15:16 UTC, semanticmx commented on cap3-elements/README.md
> +# HTML5 Elements
Este pull request incluye archivos del PR #12 que no deberían aparecer, no hay nada que hacer solo hay que revisar el proceso de creación de branches para que solo se muestren los cambios nuevos en el PR

2021-10-25 20:33 UTC, semanticmx commented
@JosephColinP de este PR falta actualizar algo?

2021-10-25 20:51 UTC, JosephColinP commented
> @JosephColinP de este PR falta actualizar algo?

No, de este ya quedó, ya había editado el tag :)

2021-10-25 20:59 UTC, semanticmx approved these changes

2021-10-25 20:59 UTC, merged