Ch.3 Elements
semanticmx/html5_082021 pull request #6
Opened 2021-09-14 16:56 UTC by JosephColinP

## what

- Added new folder
- Added index.html
- Added style.css

## why

- The PR was created to clarify HTML5 semantic elements and structure
- Added style.css just as a visual reference 

## References

- http://diveintohtml5.info/semantics.html

2021-09-14 17:30 UTC, semanticmx requested changes
perfecto

2021-09-14 17:30 UTC, semanticmx commented on cap1-mime-type/Index.html
> +
index.html en minúscula por favor.

2021-09-14 17:30 UTC, semanticmx commented on cap2-detecting-features/README.md
> +    // let's draw some shapes!
hay que identar los ejemplos, `// let's draw some shapes!` debe ir identado.

2021-09-14 17:30 UTC, semanticmx commented on cap2-detecting-features/index.html
> +
hay que tratar de no colocar espacios de más.

Solo debería haber una línea de separación entre bloques de código

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/README.md
> +``` <head> </head> ```
cuando hay etiquetas vacias hay que dejarlas sin espacios.

Para el interprete del navegador no importa cuantos espacios haya, es solo un ajuste de estilo de código.

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/README.md
> +<mark> Highlight a text </mark>
El espacio que hay antes y después del contenido de la etiqueta no va y tampoco aparecería en el navegador. Este si hay que quitarlo porque no tiene efecto en el código

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/index.html
> +
este espacio sobra

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css" >
cuando una etiqueta tenga más de un atributo hay que listara de esta forma:

```
<link
  rel="stylesheet"
  type="text/css"
  href="style.css">
```

Y el espacio al final entre las comillas y el mayor que no va.

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/index.html
> +        <p>Este este un <mark>mark</mark> tag </p>
hay que quitar el espacio al final de "tag"

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/index.html
> +    <link rel="stylesheet" type="text/css" href="style.css" >
@JosephColinP esto hay que agregarlo a los estandares

2021-09-14 17:30 UTC, semanticmx commented on cap3-elements/style.css
> +    background-color: #2a437a;
para CSS, los atributos tienen que ir en orden alfabético.

@JosephColinP esto hay que agregarlo a los estandares aunque estrictamente es un tema de CSS

2021-09-14 22:16 UTC, JosephColinP commented
Porque salen los conflictos?

2021-09-14 22:17 UTC, JosephColinP commented on cap3-elements/style.css
> +    background-color: #2a437a;
Vale vale, eso es algo nuevo, gracias

2021-09-20 16:21 UTC, semanticmx commented
@JosephColinP cuando termines los ajustes podrías resolvver los conflictos que marca GitHub? en los archivos README.md e index.html?

2021-10-06 13:23 UTC, semanticmx commented
cerrando este PR ya que los cambios se incluyen en el PR #7

2021-10-06 13:23 UTC, closed without merging